# Restaurants Data Cleaning By Oluwatimilehin Olugbade

In [3]:
import pandas as pd

### Loading dataset using panda

In [4]:
Data = pd.read_csv('zomato.csv', low_memory= False)

In [5]:
print("First 5 records:", Data.head())

First 5 records:                                                  url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...
1  https://www.zomato.com/bangalore/spice-elephan...
2  https://www.zomato.com/SanchurroBangalore?cont...
3  https://www.zomato.com/bangalore/addhuri-udupi...
4  https://www.zomato.com/bangalore/grand-village...

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233
1          Yes         No  4.1/5    787                      080 41714161
2          Yes         No  3.8/5    918                    +91 9663487993
3           No         No  3.7/5     88                    +91 9620009302
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005

       location            rest_type  \
0  Banashankari        Casual Dining
1  Banashankari        Casual Dining
2  Banashankari  Cafe, Casual Dining
3  Banashankari          Quick Bites
4  Basavanagudi        Casual Dining

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                        Masala Dosa
4                                Panipuri, Gol Gappe

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                         800
1     Chinese, North Indian, Thai                         800
2          Cafe, Mexican, Italian                         800
3      South Indian, North Indian                         300
4        North Indian, Rajasthani                         600

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []
3  [('Rated 4.0', "RATED\n  Great food and proper...        []
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []

  listed_in(type) listed_in(city)
0          Buffet    Banashankari
1          Buffet    Banashankari
2          Buffet    Banashankari
3          Buffet    Banashankari
4          Buffet    Banashankari

### Loading information about the dataset

In [6]:
print(Data.info())

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB
None

### Remove redundant columns

In [7]:
Data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

**Using the output above we will create a list of columns to keep and columns to drop**

In [8]:
columns_to_keep = ['name', 'online_order', 'book_table', 'dish_liked', 'rate', 'approx_cost(for two people)']
columns_to_drop = ['url', 'address', 'phone', 'votes', 'location', 'rest_type', 'cuisines', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)']

**Filtering the dataset to show only columns we want to keep**

In [9]:
Data[columns_to_keep]

,name,online_order,book_table,dish_liked,rate,approx_cost(for two people)
0,Jalsa,Yes,Yes,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",4.1/5,800
1,Spice Elephant,Yes,No,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",4.1/5,800
2,San Churro Cafe,Yes,No,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",3.8/5,800
3,Addhuri Udupi Bhojana,No,No,Masala Dosa,3.7/5,300
4,Grand Village,No,No,"Panipuri, Gol Gappe",3.8/5,600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,NaN,3.6 /5,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,"Cocktails, Pizza, Buttermilk",4.3 /5,"2,500"
51716,The Nest - The Den Bengaluru,No,No,NaN,3.4 /5,"1,500"

**Dropping(Deleting) the redundant columns permanently**

In [10]:
Data.drop(columns= columns_to_drop, inplace=True)

In [11]:
Data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

### Creating a standard column Title format for the dataset.

In [12]:
new_column_format = []
for x in Data.columns:
    new_column_format.append(x.title()) #Converts column names to Title Case

In [13]:
new_column_format

['Name',
 'Online_Order',
 'Book_Table',
 'Rate',
 'Dish_Liked',
 'Approx_Cost(For Two People)']

In [14]:
Data.columns = new_column_format #Permanentely Modifies the columns using the new title fomrat

In [15]:
Data

,Name,Online_Order,Book_Table,Rate,Dish_Liked,Approx_Cost(For Two People)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

### Drop(Delete) duplicate data

In [16]:
Data.duplicated().sum() #shows the sum of the duplicate data

np.int64(32808)

In [17]:
Data = Data.drop_duplicates() #deletes(drop) all duplicate rows in the dataset

In [18]:
Data

,Name,Online_Order,Book_Table,Rate,Dish_Liked,Approx_Cost(For Two People)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51631,Just Parathas,No,No,3.4 /5,NaN,250
51632,SeeYa Restaurant,No,No,3.3 /5,NaN,350
51641,Andhra Spices,No,No,3.2 /5,NaN,NaN
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"

### Handling NaN(Null) values in the dataset

In [19]:
Data.isna().sum() #Loads the sum of null(NaN) values in each column

Name                               0
Online_Order                       0
Book_Table                         0
Rate                            2418
Dish_Liked                     10587
Approx_Cost(For Two People)      140
dtype: int64

**Handling "Rate" column null values**

In [20]:
#The Rate column is string value so we will convert to float
Data['Rate'] = pd.to_numeric(Data['Rate'].str.split('/').str[0], errors='coerce')

In [21]:
"""
Fill missing values in the 'Rate' column using the median rating of each restaurant 
based on the restaurant name in the 'Name' column
"""
Data['Rate'] = Data.groupby('Name')['Rate'].transform(lambda x: x.fillna(x.median()))

In [22]:
"""
Attempted to fill missing 'Rate' values using the median rating per restaurant, but it did not work 
because many missing values belong to restaurants with no existing ratings (all NaN).
Since these entries do not contribute meaningful information for EDA, they will be dropped from the dataset.
"""
Data.dropna(subset=["Rate"], inplace=True)

**Handling "Dish_Liked" column null values**

In [23]:
"""
Fill missing values in the 'Dish_Liked' column using the mode value of each restaurant 
based on the restaurant name in the 'Name' column. if the restuarant happens to not have a dishlike value, 
we will fill as "Unknown"
"""
Data['Dish_Liked'] = Data.groupby('Name')['Dish_Liked'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown')
)

**Handling "Approx_Cost(For Two People)" column null values**

In [24]:
#converting the data type to int
Data['Approx_Cost(For Two People)'] = Data['Approx_Cost(For Two People)'].astype(str).str.replace(',', '') #remove commas in our values
Data['Approx_Cost(For Two People)'] = pd.to_numeric(Data['Approx_Cost(For Two People)'], errors='coerce').astype('Int64')

In [25]:
"""
Fill missing values in this column using the median value of each restaurant 
based on the restaurant name in the 'Name' column
"""
Data['Approx_Cost(For Two People)'] = Data.groupby('Name')['Approx_Cost(For Two People)'].transform(lambda x: x.fillna(x.median()))

In [26]:
#check null values in Approx_Cost(For Two People) column
Data['Approx_Cost(For Two People)'].isna().sum()

np.int64(33)

In [27]:
"""
There's still some NaN Values in the Approx_Cost(For Two People) column. 
I will be filling them using the general median
"""
Data['Approx_Cost(For Two People)'] = Data['Approx_Cost(For Two People)'].fillna(
    Data['Approx_Cost(For Two People)'].median())

In [28]:
Data.isna().sum() #loading the sum of the null values, to confirm that i have succesfully removed all null values

Name                           0
Online_Order                   0
Book_Table                     0
Rate                           0
Dish_Liked                     0
Approx_Cost(For Two People)    0
dtype: int64

### Cleaning individual columns

In [29]:
#Cleaning values in the "Name" column with weird characters
Data['Name'][10] #This is an example of such weird value

'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x83Ã\x83Â\x83Ã\x82Â\x82Ã\x83Â\x82Ã\x82Â© Down The Alley'

In [30]:
Data['Name'] = Data['Name'].str.replace(r'[^\x00-\x7F]+', '', regex=True)

In [31]:
Data['Name'][10] #checking if this solved the problem with the characters

'Caf Down The Alley'

In [32]:
#cleaning extra spaces in the "Name" and "Dish_Liked" column
Data[['Name', 'Dish_Liked']] = Data[['Name', 'Dish_Liked']].apply(lambda col: col.str.strip())

In [33]:
#change column name from "rate" to "ratings"
Data.rename(columns = {"Rate": "Ratings"}, inplace=True)

In [34]:
#resetting the index because we dropped some rows earlier 
Data.reset_index(inplace=True)

In [35]:
Data.columns

Index(['index', 'Name', 'Online_Order', 'Book_Table', 'Ratings', 'Dish_Liked',
       'Approx_Cost(For Two People)'],
      dtype='str')

In [36]:
#dropping the old index
Data.drop(columns= ['index'], inplace= True)

### Exporting the cleaned dataset

In [37]:
#Exporting the cleaned dataset to a csv file
Data.to_csv('cleaned_restaurant_data.csv', index= False)

In [38]:
#Exporting the cleaned data to an Excel file
Data.to_excel('cleaned_restaurant_data.xlsx', index= False)